spring:
  application:
    name: WebsiteDaiHocDienTu
  datasource:
    url: jdbc:mysql://localhost:3306/ttcn_nhom2
    username: ttcnNhom2
    password: ttcnNhom2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
