spring:
  application:
    name: WebsiteDaiHocDienTu
  datasource:
    url: jdbc:mysql://localhost:3306/ttcn-nhom2
    username: ttcnNhom2
    password: ttcnNhom2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true




    #
# JDBC properties
#

#
# turn off the spring boot banner
#


#
# reduce logging level. Set loggin level to warn
#
#logging.level.root=warn

#
# show jpa/hibernate logging message
#
    # ghi lai cac lenh sql
#Logging.level.org.hibernate.SQL=trace
    # ghi lai cac tri trong cau lenh SQL
#Logging.level.org.hibernate.orm.jdbc.bind=trace

